export const ANALYSIS_ENGINE_VERSION = "1.0.0";
export const ANALYSIS_ENGINE_ID = "ecolab.stage4.analysis";
export const ANALYSIS_ENGINE_STABLE_ID = ANALYSIS_ENGINE_ID;
export const ANALYSIS_STABLE_ID = ANALYSIS_ENGINE_ID;
export const ANALYSIS_IMPLEMENTATION_ID = "ecolab-stage4-analysis-v1";
export const ANALYSIS_ENGINE_IMPLEMENTATION_ID = ANALYSIS_IMPLEMENTATION_ID;
